# Generated by Django 5.1.6 on 2025-04-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('puzzle_type', models.CharField(max_length=32)),
                ('puzzle_class', models.CharField(max_length=32)),
                ('puzzle_data', models.JSONField()),
            ],
            options={
                'db_table': 'generated_puzzles',
                'ordering': ['-created_at'],
            },
        ),
    ]
