import uuid
import random

from django.db import models


class Visitor(models.Model):
    """
    Represents an anonymous visitor, tied to a long-lived HttpOnly cookie.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    generated_username = models.CharField(max_length=50, unique=True, null=True, editable=False)
    last_seen = models.DateTimeField(auto_now=True)
    user_agent = models.TextField()

    class Meta:
        indexes = [models.Index(fields=["last_seen"])]

    def set_readable_username(self):
        """Generate a more readable username using word lists"""
        adjectives = [
            # Colors
            "red",
            "blue",
            "green",
            "gold",
            "silver",
            "purple",
            "orange",
            "pink",
            "yellow",
            "black",
            "white",
            "gray",
            "crimson",
            "azure",
            "emerald",
            "violet",
            "amber",
            "ruby",
            "sapphire",
            "jade",
            "coral",
            "navy",
            # Personality/Traits
            "brave",
            "quick",
            "clever",
            "bright",
            "swift",
            "bold",
            "keen",
            "wise",
            "calm",
            "cool",
            "sharp",
            "smart",
            "strong",
            "wild",
            "free",
            "pure",
            "royal",
            "noble",
            "proud",
            "mighty",
            "grand",
            "epic",
            "super",
            "mega",
            "fierce",
            "gentle",
            "lucky",
            "happy",
            "cheerful",
            "silent",
            "loud",
            "shy",
            "sneaky",
            "honest",
            "loyal",
            "funny",
            "serious",
            "playful",
            # Size/Intensity
            "giant",
            "tiny",
            "huge",
            "mini",
            "massive",
            "small",
            "big",
            "little",
            "vast",
            "micro",
            "jumbo",
            "petite",
            "colossal",
            "mighty",
            # Weather/Nature
            "sunny",
            "stormy",
            "windy",
            "misty",
            "frosty",
            "snowy",
            "rainy",
            "cloudy",
            "foggy",
            "starry",
            "moonlit",
            "frozen",
            "blazing",
            # Mystery/Magic
            "mystic",
            "magic",
            "cosmic",
            "stellar",
            "lunar",
            "solar",
            "astral",
            "phantom",
            "shadow",
            "ghost",
            "spirit",
            "ancient",
            "eternal",
            "crystal",
            "diamond",
            "steel",
            "iron",
            "bronze",
            "platinum",
        ]

        animals = [
            # Common Animals
            "cat",
            "dog",
            "bird",
            "fish",
            "rabbit",
            "mouse",
            "horse",
            "cow",
            "pig",
            "sheep",
            "goat",
            "duck",
            "chicken",
            "turkey",
            "deer",
            # Wild Animals
            "tiger",
            "lion",
            "elephant",
            "giraffe",
            "zebra",
            "rhino",
            "hippo",
            "wolf",
            "fox",
            "bear",
            "panda",
            "koala",
            "kangaroo",
            "monkey",
            "gorilla",
            "cheetah",
            "leopard",
            "jaguar",
            "lynx",
            "bobcat",
            "puma",
            "cougar",
            "panther",
            "hyena",
            "jackal",
            "coyote",
            "raccoon",
            "skunk",
            "otter",
            "beaver",
            "badger",
            "mole",
            "hedgehog",
            "porcupine",
            # Ocean Animals
            "shark",
            "whale",
            "dolphin",
            "seal",
            "octopus",
            "squid",
            "crab",
            "lobster",
            "shrimp",
            "jellyfish",
            "starfish",
            "seahorse",
            "turtle",
            "penguin",
            "walrus",
            "stingray",
            "barracuda",
            "swordfish",
            "tuna",
            # Birds
            "eagle",
            "hawk",
            "falcon",
            "owl",
            "raven",
            "crow",
            "parrot",
            "peacock",
            "swan",
            "flamingo",
            "pelican",
            "heron",
            "crane",
            "stork",
            "robin",
            "sparrow",
            "cardinal",
            "bluejay",
            "woodpecker",
            "hummingbird",
            # Reptiles & Amphibians
            "snake",
            "lizard",
            "gecko",
            "iguana",
            "chameleon",
            "turtle",
            "tortoise",
            "alligator",
            "crocodile",
            "frog",
            "toad",
            "salamander",
            "cobra",
            "python",
            "viper",
            "rattlesnake",
            # Insects & Others
            "butterfly",
            "dragonfly",
            "beetle",
            "spider",
            "scorpion",
            "mantis",
            "cricket",
            "grasshopper",
            "firefly",
            "ladybug",
            "bee",
            "wasp",
            # Mythical/Fantasy (fun additions)
            "dragon",
            "phoenix",
            "unicorn",
            "griffin",
            "pegasus",
            "basilisk",
            "sphinx",
            "kraken",
            "hydra",
            "chimera",
        ]

        random.seed(str(self.id))

        adjective = random.choice(adjectives)
        animal = random.choice(animals)

        uuid_int = int(str(self.id).replace("-", "")[:8], 16)
        number = uuid_int % 100

        self.generated_username = f"{adjective}-{animal}-{number:02d}"

