# Generated by Django 5.2.3 on 2025-06-18 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_username",
                    models.CharField(
                        editable=False, max_length=50, null=True, unique=True
                    ),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("user_agent", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_seen"], name="tracking_vi_last_se_eb49db_idx"
                    )
                ],
            },
        ),
    ]
