name: mitpuzzles
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: ["..:/workspace:cached"]
    command: sleep infinity
    environment:
      PYTHONPATH: /workspace/backend

  postgres:
    image: postgres:18rc1
    restart: unless-stopped
    volumes: [postgres-data-18:/var/lib/postgresql/data]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mitpuzzles
    ports: ["5432:5432"]

volumes:
  postgres-data:
  postgres-data-18:
