"""create puzzle table

Revision ID: 0474e76e4d4e
Revises: 133201b3ba04
Create Date: 2025-09-03 08:38:57.451570

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0474e76e4d4e"
down_revision: Union[str, Sequence[str], None] = "75f9fd5a89d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "puzzle",
        sa.Column("id", sa.UUID(), nullable=False, server_default=sa.text("uuidv7()")),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("complete_id", sa.String(length=36), nullable=False),
        sa.Column("definition_id", sa.String(length=36), nullable=False),
        sa.Column("solution_id", sa.String(length=36), nullable=False),
        sa.Column("puzzle_type", sa.String(length=32), nullable=False),
        sa.Column("puzzle_size", sa.String(length=32), nullable=False),
        sa.Column("puzzle_difficulty", sa.String(length=32), nullable=True),
        sa.Column("puzzle_data", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("complete_id"),
    )
    op.create_index("idx_puzzle_difficulty", "puzzle", ["puzzle_difficulty"], unique=False)
    op.create_index("idx_puzzle_type", "puzzle", ["puzzle_type"], unique=False)
    op.create_index(
        "idx_puzzle_type_size_difficulty",
        "puzzle",
        ["puzzle_type", "puzzle_size", "puzzle_difficulty"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_puzzle_type_size_difficulty", table_name="puzzle")
    op.drop_index("idx_puzzle_type", table_name="puzzle")
    op.drop_index("idx_puzzle_difficulty", table_name="puzzle")
    op.drop_table("puzzle")
    # ### end Alembic commands ###
