"""add device tables

Revision ID: e75100b1355d
Revises:
Create Date: 2025-08-31 00:29:53.195091

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e75100b1355d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_agent", sa.String(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "device_thumbmark",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(), nullable=False),
        sa.Column("thumbmark_id", sa.String(), nullable=False),
        sa.Column("thumbmark_data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("device_thumbmark")
    op.drop_table("device")
    # ### end Alembic commands ###
