"""create freeplay attempt table

Revision ID: 6239e0f9e8df
Revises: 0474e76e4d4e
Create Date: 2025-09-07 00:14:31.043392

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "6239e0f9e8df"
down_revision: Union[str, Sequence[str], None] = "0474e76e4d4e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "freeplay_puzzle_attempt",
        sa.Column("id", sa.UUID(), nullable=False, server_default=text("uuidv7()")),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("puzzle_id", sa.UUID(), nullable=True),
        sa.Column("timestamp_start", sa.BigInteger(), nullable=False),
        sa.Column("timestamp_finish", sa.BigInteger(), nullable=True),
        sa.Column("action_history", sa.JSON(), nullable=False),
        sa.Column("board_state", sa.JSON(), nullable=False),
        sa.Column("used_tutorial", sa.Boolean(), nullable=False),
        sa.Column("is_solved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["device.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["puzzle_id"], ["puzzle.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_freeplay_device_puzzle",
        "freeplay_puzzle_attempt",
        ["device_id", "puzzle_id"],
        unique=False,
    )
    op.create_index("idx_freeplay_is_solved", "freeplay_puzzle_attempt", ["is_solved"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_freeplay_is_solved", table_name="freeplay_puzzle_attempt")
    op.drop_index("idx_freeplay_device_puzzle", table_name="freeplay_puzzle_attempt")
    op.drop_table("freeplay_puzzle_attempt")
    # ### end Alembic commands ###
