"""add session_activity table

Revision ID: 7ac06957b098
Revises: 4b92c6b85e47
Create Date: 2025-10-09 00:58:47.546416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac06957b098'
down_revision: Union[str, Sequence[str], None] = '4b92c6b85e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('initial_referrer', sa.String(length=2048), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_device_started', 'session_activity', ['device_id', 'started_at'], unique=False)
    op.create_index('idx_session_user_started', 'session_activity', ['user_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_session_activity_session_id'), 'session_activity', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_activity_session_id'), table_name='session_activity')
    op.drop_index('idx_session_user_started', table_name='session_activity')
    op.drop_index('idx_session_device_started', table_name='session_activity')
    op.drop_index('idx_session_active', table_name='session_activity')
    op.drop_table('session_activity')
    # ### end Alembic commands ###
