"""add puzzle_priority and puzzle_shown tables

Revision ID: 7af9bd68351f
Revises: 7ac06957b098
Create Date: 2025-10-29 07:12:16.305403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af9bd68351f'
down_revision: Union[str, Sequence[str], None] = '7ac06957b098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_priority',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_priority_active', 'puzzle_priority', ['puzzle_id', 'added_at', 'removed_at'], unique=False)
    op.create_table('puzzle_shown',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('puzzle_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('was_priority', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['freeplay_puzzle_attempt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzle.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id')
    )
    op.create_index('idx_shown_at', 'puzzle_shown', ['shown_at'], unique=False)
    op.create_index('idx_shown_device_puzzle', 'puzzle_shown', ['device_id', 'puzzle_id'], unique=False)
    op.create_index('idx_shown_device_unique', 'puzzle_shown', ['device_id', 'puzzle_id'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_index('idx_shown_session', 'puzzle_shown', ['session_id'], unique=False)
    op.create_index('idx_shown_user_puzzle', 'puzzle_shown', ['user_id', 'puzzle_id'], unique=False)
    op.create_index('idx_shown_user_unique', 'puzzle_shown', ['user_id', 'puzzle_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_index('idx_session_ended_at', 'session_activity', ['ended_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_ended_at', table_name='session_activity')
    op.drop_index('idx_shown_user_unique', table_name='puzzle_shown', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_shown_user_puzzle', table_name='puzzle_shown')
    op.drop_index('idx_shown_session', table_name='puzzle_shown')
    op.drop_index('idx_shown_device_unique', table_name='puzzle_shown', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index('idx_shown_device_puzzle', table_name='puzzle_shown')
    op.drop_index('idx_shown_at', table_name='puzzle_shown')
    op.drop_table('puzzle_shown')
    op.drop_index('idx_priority_active', table_name='puzzle_priority')
    op.drop_table('puzzle_priority')
    # ### end Alembic commands ###
