"""add background job tables

Revision ID: 9aa6497bcb10
Revises: 3911cae570eb
Create Date: 2025-12-12 19:44:24.799623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa6497bcb10'
down_revision: Union[str, Sequence[str], None] = '3911cae570eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_job',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('puzzle_type', sa.String(length=32), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_data', sa.JSON(), nullable=True),
    sa.Column('total_puzzles', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('unique_count', sa.Integer(), nullable=False),
    sa.Column('multi_solution_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('disabled_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_background_job_created', 'background_job', ['created_at'], unique=False)
    op.create_index('idx_background_job_status', 'background_job', ['status'], unique=False)
    op.create_index('idx_background_job_type', 'background_job', ['job_type'], unique=False)
    op.create_table('analysis_job_puzzle',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_index', sa.Integer(), nullable=False),
    sa.Column('puzzle_data', sa.JSON(), nullable=False),
    sa.Column('definition_id', sa.String(length=36), nullable=False),
    sa.Column('solution_id', sa.String(length=36), nullable=False),
    sa.Column('complete_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('solutions', sa.JSON(), nullable=True),
    sa.Column('solution_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('imported_puzzle_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['imported_puzzle_id'], ['puzzle.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['background_job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_puzzle_complete_id', 'analysis_job_puzzle', ['complete_id'], unique=False)
    op.create_index('idx_analysis_puzzle_job', 'analysis_job_puzzle', ['job_id'], unique=False)
    op.create_index('idx_analysis_puzzle_result', 'analysis_job_puzzle', ['result'], unique=False)
    op.create_index('idx_analysis_puzzle_status', 'analysis_job_puzzle', ['status'], unique=False)

    # Add is_active column to puzzle table
    op.add_column('puzzle', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE puzzle SET is_active = true WHERE is_active IS NULL")
    op.alter_column('puzzle', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'is_active')
    op.drop_index('idx_analysis_puzzle_status', table_name='analysis_job_puzzle')
    op.drop_index('idx_analysis_puzzle_result', table_name='analysis_job_puzzle')
    op.drop_index('idx_analysis_puzzle_job', table_name='analysis_job_puzzle')
    op.drop_index('idx_analysis_puzzle_complete_id', table_name='analysis_job_puzzle')
    op.drop_table('analysis_job_puzzle')
    op.drop_index('idx_background_job_type', table_name='background_job')
    op.drop_index('idx_background_job_status', table_name='background_job')
    op.drop_index('idx_background_job_created', table_name='background_job')
    op.drop_table('background_job')
    # ### end Alembic commands ###
