"""add generated_export table

Revision ID: 30dc369587c0
Revises: 9aa6497bcb10
Create Date: 2026-02-18 12:03:04.729850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30dc369587c0'
down_revision: Union[str, Sequence[str], None] = '9aa6497bcb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_export',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('compression', sa.String(length=16), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_hash')
    )
    op.create_index('idx_generated_export_created_at', 'generated_export', ['created_at'], unique=False)
    op.create_index('idx_generated_export_query_hash', 'generated_export', ['query_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_generated_export_query_hash', table_name='generated_export')
    op.drop_index('idx_generated_export_created_at', table_name='generated_export')
    op.drop_table('generated_export')
    # ### end Alembic commands ###
