"""add metrics column to puzzle

Revision ID: 6c63099f8841
Revises: 040fdcd49688
Create Date: 2026-03-30 07:42:38.609828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c63099f8841'
down_revision: Union[str, Sequence[str], None] = '040fdcd49688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puzzle', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puzzle', 'metrics')
    # ### end Alembic commands ###
