"""add metrics column to freeplay_puzzle_attempt

Revision ID: 424b63de233d
Revises: 6c63099f8841
Create Date: 2026-03-31 03:57:58.319375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '424b63de233d'
down_revision: Union[str, Sequence[str], None] = '6c63099f8841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freeplay_puzzle_attempt', sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('freeplay_puzzle_attempt', 'metrics')
    # ### end Alembic commands ###
