"""add user_leaderboard_score table

Revision ID: a3b907c531a2
Revises: 424b63de233d
Create Date: 2026-04-14 21:58:56.900112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b907c531a2'
down_revision: Union[str, Sequence[str], None] = '424b63de233d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_leaderboard_score',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('puzzle_type', sa.String(length=50), nullable=False),
    sa.Column('puzzle_size', sa.String(length=20), nullable=False),
    sa.Column('puzzle_difficulty', sa.String(length=20), nullable=False),
    sa.Column('score_type', sa.String(length=10), nullable=False),
    sa.Column('time_ms', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'puzzle_type', 'puzzle_size', 'puzzle_difficulty', 'score_type', name='uq_user_leaderboard_score')
    )
    op.create_index('idx_leaderboard_lookup', 'user_leaderboard_score', ['puzzle_type', 'puzzle_size', 'puzzle_difficulty', 'score_type', 'time_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leaderboard_lookup', table_name='user_leaderboard_score')
    op.drop_table('user_leaderboard_score')
    # ### end Alembic commands ###
