services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: mitlogic
      POSTGRES_PASSWORD: mitlogic
      POSTGRES_DB: mitlogic
    ports: ["5432:5432"]
    volumes: [mitlogic_postgres_data:/var/lib/postgresql/data]

  valkey:
    image: redis
    ports: ["6379:6379"]

  pgadmin:
    image: dpage/pgadmin4
    ports: ["5050:80"]
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports: ["1234:8000"]
    environment:
      DATABASE_URL: postgres://mitlogic:mitlogic@postgres:5432/mitlogic


volumes:
  mitlogic_postgres_data:
