import { addIcons } from "oh-vue-icons";
export { OhVueIcon } from "oh-vue-icons";

import {
  FaUndoAlt,
  FaRedoAlt,
  IoCloseSharp,
  HiCheck,
  MdFibernew,
  FaCheckCircle,
  IoClose,
  HiInformationCircle,
  MdLeaderboard,
  BiLightbulbFill,
  MdArrowdropdown,
  IoSettingsOutline,
  BiArrowRightCircle,
  BiCheckCircleFill,
  BiCircle,
  BiCircleFill,
  BiRecordCircleFill,
  BiArrowRightSquareFill,
  BiLayoutSidebarInset,
  BiMoonStarsFill,
  BiSunFill,
  BiChevronDoubleUp,
  BiCheck,
  HiPencilAlt,
  BiInfoCircleFill,
  MdFeedbackOutlined,
  CoMagnifyingGlass,
  FaRegularArrowAltCircleRight,
  FaGoogle,
  FaUser,
} from "oh-vue-icons/icons";

addIcons(
  FaUndoAlt,
  FaRedoAlt,
  IoCloseSharp,
  HiCheck,
  MdFibernew,
  FaCheckCircle,
  IoClose,
  HiInformationCircle,
  MdLeaderboard,
  BiLightbulbFill,
  MdArrowdropdown,
  IoSettingsOutline,
  BiArrowRightCircle,
  BiCheckCircleFill,
  BiCircle,
  BiCircleFill,
  BiRecordCircleFill,
  BiArrowRightSquareFill,
  BiLayoutSidebarInset,
  BiMoonStarsFill,
  BiSunFill,
  BiChevronDoubleUp,
  BiCheck,
  HiPencilAlt,
  BiInfoCircleFill,
  MdFeedbackOutlined,
  CoMagnifyingGlass,
  FaRegularArrowAltCircleRight,
  FaGoogle,
  FaUser
);
