# Generated by Django 5.2.3 on 2025-07-07 15:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Puzzle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("puzzle_hash", models.CharField(max_length=64, unique=True)),
                ("puzzle_type", models.CharField(max_length=32)),
                ("puzzle_size", models.CharField(max_length=32)),
                ("puzzle_difficulty", models.CharField(max_length=32)),
                ("puzzle_data", models.JSONField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FreeplayPuzzleAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_time_client_ms", models.FloatField(blank=True, null=True)),
                ("action_history", models.JSONField(blank=True, default=list)),
                ("used_tutorial", models.BooleanField(default=False)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracking.visitor",
                    ),
                ),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="puzzles.puzzle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freeplay Puzzle Attempt",
                "verbose_name_plural": "Freeplay Puzzle Attempts",
            },
        ),
    ]
