# Generated by Django 5.2.3 on 2025-06-24 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0001_initial"),
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreeplayPuzzleAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_time_client", models.FloatField(blank=True, null=True)),
                ("board_state", models.JSONField()),
                ("action_history", models.JSONField(blank=True, default=list)),
                ("is_solved", models.BooleanField(default=False)),
                ("used_tutorial", models.BooleanField(default=False)),
                (
                    "puzzle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="puzzles.puzzle",
                    ),
                ),
                (
                    "visitor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tracking.visitor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Freeplay Puzzle Attempt",
                "verbose_name_plural": "Freeplay Puzzle Attempts",
            },
        ),
        migrations.DeleteModel(
            name="ActivePuzzleSession",
        ),
    ]
