# Generated by Django 5.2.3 on 2025-06-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0002_freeplaypuzzleattempt_delete_activepuzzlesession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freeplaypuzzleattempt",
            old_name="visitor_id",
            new_name="visitor",
        ),
    ]
