# Generated by Django 5.2.3 on 2025-06-26 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0003_rename_visitor_id_freeplaypuzzleattempt_visitor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freeplaypuzzleattempt",
            old_name="completion_time_client",
            new_name="completion_time_client_ms",
        ),
    ]
