# Generated by Django 5.2.3 on 2025-07-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "puzzles",
            "0004_rename_completion_time_client_freeplaypuzzleattempt_completion_time_client_ms",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PuzzleAttempt",
        ),
    ]
