# Generated by Django 5.2.3 on 2025-07-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0005_delete_puzzleattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freeplaypuzzleattempt",
            name="board_state",
        ),
    ]
