# Generated by Django 5.2.3 on 2025-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("puzzles", "0006_remove_freeplaypuzzleattempt_board_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freeplaypuzzleattempt",
            name="is_solved",
        ),
    ]
