# Generated by Django 5.1.6 on 2025-04-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(),
        ),
    ]
